name: csv
version: 8.0.0
description: |-
  A high-quality CSV library. Encode and decode CSV strings, with
  stream support (one row per event), auto-detection, and Excel compatibility.

  The string must be comma (configurable) separated values.
homepage: https://github.com/close2/csv
documentation: https://github.com/close2/csv

environment:
  sdk: ^3.10.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
